[project]
name = "resume-generator"
version = "0.1.0"
description = "A script to generate a PDF and HTML resume from a template"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jinja2>=3.1.6",
    "pyyaml>=6.0.3",
]
